---
# tasks file for proxmox
- name: Ensure gpg is installed
  ansible.builtin.apt:
    name: gpg
    state: latest

- name: Add Proxmox gpg key
  ansible.builtin.apt_key:
    url: "http://download.proxmox.com/debian/{{ proxmox_release }}"
    state: present

- name: Add Proxmox pve-no-subscription repo
  ansible.builtin.apt_repository:
    repo: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
    filename: pve-no-subscription
    state: present

- name: Only run "update_cache=yes" if the last one is more than 86400 seconds (1 day) ago
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Upgrade the OS (apt full-upgrade)
  ansible.builtin.apt:
    upgrade: full

- name: Install Proxmox VE packages
  ansible.builtin.apt:
    name:
      - proxmox-ve
      - postfix
      - open-iscsi
    state: present

- name: Disable Proxmox pve-enterprise repo
  ansible.builtin.lineinfile:
    regexp: '(^deb .*)'
    line: '# \1'
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: present


- name: Ensure "os-prober" is uninstalled
  ansible.builtin.apt:
    name: os-prober
    state: absent

- name: Ensure "ifupdown2" is installed
  ansible.builtin.apt:
    name: ifupdown2
    state: present

- name: Check if a reboot is needed for Debian and Ubuntu boxes
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_checksum: no
  register: reboot_required

- name: Notify Reboot Handler if required
  ansible.builtin.assert:
    that: true
    quiet: true
  changed_when: true
  when: reboot_required.stat.exists
  notify: "Reboot Proxmox Host"
