---
# tasks file for proxmox
- name: Add Proxmox pve-no-subscription repo
  ansible.builtin.apt_repository:
    repo: "deb http://download.proxmox.com/debian/pve {{ proxmox_release }} pve-no-subscription"
    filename: pve-no-subscription
    state: present
