---
# tasks file for proxmox
- name: Ensure gpg is installed
  apt:
    name: gpg
    state: latest

- name: Add Proxmox gpg key
  ansible.builtin.apt_key:
    url: "http://download.proxmox.com/debian/{{ proxmox_release }}"
    state: present

- name: Add Proxmox pve-no-subscription repo
  ansible.builtin.apt_repository:
    repo: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
    filename: pve-no-subscription
    state: present
